import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Header, Footer } from "../components";
import { AnalyticsProvider } from "../contexts/AnalyticsContext";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AnalyticsProvider
          config={{
            enabled: true,
            debug: process.env.NODE_ENV === 'development',
            trackingId: process.env.NEXT_PUBLIC_GA_TRACKING_ID,
            endpoint: process.env.NEXT_PUBLIC_ANALYTICS_ENDPOINT,
          }}
        >
          <div className="page-container">
            <Header />
            <main className="main-content">
              <div className="main-content-inner">{children}</div>
            </main>
            <Footer />
          </div>
        </AnalyticsProvider>
      </body>
    </html>
  );
}
